import api from './api';

export interface LoyaltyCardConfig {
  id: string;
  loyalty_card_name: string;
  loyalty_card_code: string;
  card_color?: string;
  entrance_points: number;
  allow_gaining_cash_sales: boolean;
  allow_gaining_credit_sales: boolean;
  is_default: boolean;
  redemption_rate?: number;
  minimum_redemption_points?: number;
  maximum_redemption_points?: number;
  birthday_bonus_points?: number;
  welcome_bonus_points?: number;
  // Gain Rates Configuration
  gain_rate_lower_limit?: number;
  gain_rate_upper_limit?: number;
  gain_rate_type?: 'fixed' | 'percentage';
  gain_rate_value?: number;
  // Discount Rates Configuration
  discount_rate_lower_limit?: number;
  discount_rate_upper_limit?: number;
  discount_rate_type?: 'fixed' | 'percentage';
  discount_rate_value?: number;
  is_active: boolean;
  created_by: string;
  updated_by?: string;
  created_at: string;
  updated_at?: string;
  // Audit fields
  created_by_name?: string;
  updated_by_name?: string;
}

export interface LoyaltyCard {
  id: string;
  loyalty_config_id: string;
  card_number: string;
  customer_name: string;
  customer_email?: string;
  customer_phone?: string;
  current_points: number;
  total_points_earned: number;
  total_points_redeemed: number;
  tier_level: 'bronze' | 'silver' | 'gold' | 'platinum';
  tier_points_threshold: number;
  is_active: boolean;
  issued_date: string;
  last_used_date?: string;
  expiry_date?: string;
  notes?: string;
  created_by: string;
  updated_by?: string;
  created_at: string;
  updated_at?: string;
  // Include config details for display
  loyalty_config?: LoyaltyCardConfig;
}

export interface LoyaltyConfig {
  id: string;
  config_name: string;
  points_per_dollar: number;
  redemption_rate: number;
  minimum_redemption_points: number;
  maximum_redemption_percentage: number;
  points_expiry_days?: number | null;
  tier_bronze_threshold: number;
  tier_silver_threshold: number;
  tier_gold_threshold: number;
  tier_platinum_threshold: number;
  birthday_bonus_points: number;
  welcome_bonus_points: number;
  is_active: boolean;
  created_by: string;
  updated_by?: string;
  created_at: string;
  updated_at?: string;
}

export interface LoyaltyTransaction {
  id: string;
  loyalty_card_id: string;
  transaction_type: 'earn' | 'redeem' | 'expire' | 'adjust' | 'bonus';
  points_amount: number;
  transaction_reference?: string;
  description?: string;
  order_id?: string;
  points_balance_before: number;
  points_balance_after: number;
  tier_before?: string;
  tier_after?: string;
  transaction_date: string;
  expiry_date?: string;
  is_expired: boolean;
  created_by: string;
  created_at: string;
}

export interface CreateLoyaltyCardConfigRequest {
  loyalty_card_name: string;
  loyalty_card_code?: string; // Optional - auto-generated by backend
  card_color?: string;
  entrance_points: number;
  allow_gaining_cash_sales: boolean;
  allow_gaining_credit_sales: boolean;
  is_default?: boolean;
  redemption_rate?: number;
  minimum_redemption_points?: number;
  maximum_redemption_points?: number;
  birthday_bonus_points?: number;
  welcome_bonus_points?: number;
  // Gain Rates Configuration
  gain_rate_lower_limit?: number;
  gain_rate_upper_limit?: number;
  gain_rate_type?: 'fixed' | 'percentage';
  gain_rate_value?: number;
  // Discount Rates Configuration
  discount_rate_lower_limit?: number;
  discount_rate_upper_limit?: number;
  discount_rate_type?: 'fixed' | 'percentage';
  discount_rate_value?: number;
}

export interface UpdateLoyaltyCardConfigRequest {
  loyalty_card_name?: string;
  loyalty_card_code?: string;
  card_color?: string;
  entrance_points?: number;
  allow_gaining_cash_sales?: boolean;
  allow_gaining_credit_sales?: boolean;
  is_default?: boolean;
  redemption_rate?: number;
  minimum_redemption_points?: number;
  maximum_redemption_points?: number;
  birthday_bonus_points?: number;
  welcome_bonus_points?: number;
  // Gain Rates Configuration
  gain_rate_lower_limit?: number;
  gain_rate_upper_limit?: number;
  gain_rate_type?: 'fixed' | 'percentage';
  gain_rate_value?: number;
  // Discount Rates Configuration
  discount_rate_lower_limit?: number;
  discount_rate_upper_limit?: number;
  discount_rate_type?: 'fixed' | 'percentage';
  discount_rate_value?: number;
  is_active?: boolean;
}

export interface CreateLoyaltyCardRequest {
  loyalty_config_id: string;
  customer_name: string;
  customer_email?: string;
  customer_phone?: string;
  tier_level: 'bronze' | 'silver' | 'gold' | 'platinum';
  initial_points?: number;
  notes?: string;
}

export interface UpdateLoyaltyCardRequest {
  customer_name?: string;
  customer_email?: string;
  customer_phone?: string;
  tier_level?: 'bronze' | 'silver' | 'gold' | 'platinum';
  is_active?: boolean;
  notes?: string;
}

export interface AddPointsRequest {
  points: number;
  description?: string;
  order_id?: string;
}

export interface RedeemPointsRequest {
  points: number;
  description?: string;
  order_id?: string;
}

export interface CreateLoyaltyConfigRequest {
  config_name: string;
  points_per_dollar: number;
  redemption_rate: number;
  minimum_redemption_points: number;
  maximum_redemption_percentage: number;
  points_expiry_days?: number | null;
  tier_bronze_threshold: number;
  tier_silver_threshold: number;
  tier_gold_threshold: number;
  tier_platinum_threshold: number;
  birthday_bonus_points: number;
  welcome_bonus_points: number;
}

export interface LoyaltyCardsResponse {
  success: boolean;
  data: LoyaltyCard[];
  pagination: {
    total: number;
    page: number;
    limit: number;
    pages: number;
  };
}

export interface LoyaltyTransactionsResponse {
  success: boolean;
  data: LoyaltyTransaction[];
  pagination: {
    total: number;
    page: number;
    limit: number;
    pages: number;
  };
}

class LoyaltyCardService {
  // Loyalty Card Configurations
  async getLoyaltyCardConfigStats(): Promise<{ success: boolean; data: any }> {
    const response = await api.get('/loyalty-card-configs/stats');
    return response.data;
  }

  async getLoyaltyCardConfigs(params?: {
    page?: number;
    limit?: number;
    search?: string;
    status?: string;
  }): Promise<{ success: boolean; data: LoyaltyCardConfig[]; pagination: any }> {
    const queryParams = new URLSearchParams();
    
    if (params?.page) queryParams.append('page', params.page.toString());
    if (params?.limit) queryParams.append('limit', params.limit.toString());
    if (params?.search) queryParams.append('search', params.search);
    if (params?.status && params.status !== 'all') queryParams.append('status', params.status);

    const url = `/loyalty-card-configs${queryParams.toString() ? `?${queryParams.toString()}` : ''}`;
    const response = await api.get(url);
    return response.data;
  }

  async getLoyaltyCardConfig(id: string): Promise<{ success: boolean; data: LoyaltyCardConfig }> {
    const response = await api.get(`/loyalty-card-configs/${id}`);
    return response.data;
  }

  async createLoyaltyCardConfig(data: CreateLoyaltyCardConfigRequest): Promise<{ success: boolean; data: LoyaltyCardConfig; message: string }> {
    const response = await api.post('/loyalty-card-configs', data);
    return response.data;
  }

  async updateLoyaltyCardConfig(id: string, data: UpdateLoyaltyCardConfigRequest): Promise<{ success: boolean; data: LoyaltyCardConfig; message: string }> {
    const response = await api.put(`/loyalty-card-configs/${id}`, data);
    return response.data;
  }

  async deleteLoyaltyCardConfig(id: string): Promise<{ success: boolean; message: string }> {
    const response = await api.delete(`/loyalty-card-configs/${id}`);
    return response.data;
  }

  async setDefaultLoyaltyCardConfig(id: string): Promise<{ success: boolean; data: LoyaltyCardConfig; message: string }> {
    const response = await api.post(`/loyalty-card-configs/${id}/set-default`);
    return response.data;
  }

  // Loyalty Cards (Customer Cards)
  async getLoyaltyCards(params?: {
    page?: number;
    limit?: number;
    search?: string;
    tier?: string;
    status?: string;
  }): Promise<LoyaltyCardsResponse> {
    const queryParams = new URLSearchParams();
    
    if (params?.page) queryParams.append('page', params.page.toString());
    if (params?.limit) queryParams.append('limit', params.limit.toString());
    if (params?.search) queryParams.append('search', params.search);
    if (params?.tier) queryParams.append('tier', params.tier);
    if (params?.status) queryParams.append('status', params.status);

    const url = `/loyalty-cards${queryParams.toString() ? `?${queryParams.toString()}` : ''}`;
    const response = await api.get(url);
    return response.data as LoyaltyCardsResponse;
  }

  async getLoyaltyCard(id: string): Promise<{ success: boolean; data: LoyaltyCard & { recent_transactions: LoyaltyTransaction[] } }> {
    const response = await api.get(`/loyalty-cards/${id}`);
    return response.data;
  }

  async createLoyaltyCard(data: CreateLoyaltyCardRequest): Promise<{ success: boolean; data: LoyaltyCard; message: string }> {
    const response = await api.post('/loyalty-cards', data);
    return response.data;
  }

  async updateLoyaltyCard(id: string, data: UpdateLoyaltyCardRequest): Promise<{ success: boolean; data: LoyaltyCard; message: string }> {
    const response = await api.put(`/loyalty-cards/${id}`, data);
    return response.data;
  }

  async deleteLoyaltyCard(id: string): Promise<{ success: boolean; message: string }> {
    const response = await api.delete(`/loyalty-cards/${id}`);
    return response.data;
  }

  async addPoints(id: string, data: AddPointsRequest): Promise<{ success: boolean; data: any; message: string }> {
    const response = await api.post(`/loyalty-cards/${id}/add-points`, data);
    return response.data;
  }

  async redeemPoints(id: string, data: RedeemPointsRequest): Promise<{ success: boolean; data: any; message: string }> {
    const response = await api.post(`/loyalty-cards/${id}/redeem-points`, data);
    return response.data;
  }

  async getLoyaltyCardTransactions(id: string, params?: {
    page?: number;
    limit?: number;
  }): Promise<LoyaltyTransactionsResponse> {
    const queryParams = new URLSearchParams();
    
    if (params?.page) queryParams.append('page', params.page.toString());
    if (params?.limit) queryParams.append('limit', params.limit.toString());

    const url = `/loyalty-cards/${id}/transactions${queryParams.toString() ? `?${queryParams.toString()}` : ''}`;
    const response = await api.get(url);
    return response.data as LoyaltyTransactionsResponse;
  }

  // Loyalty Configuration
  async getLoyaltyConfig(): Promise<{ success: boolean; data: LoyaltyConfig }> {
    const response = await api.get('/loyalty-config');
    return response.data;
  }

  async getAllLoyaltyConfigs(): Promise<{ success: boolean; data: LoyaltyConfig[] }> {
    const response = await api.get('/loyalty-config/all');
    return response.data;
  }

  async createLoyaltyConfig(data: CreateLoyaltyConfigRequest): Promise<{ success: boolean; data: LoyaltyConfig; message: string }> {
    const response = await api.post('/loyalty-config', data);
    return response.data;
  }

  async updateLoyaltyConfig(id: string, data: Partial<CreateLoyaltyConfigRequest>): Promise<{ success: boolean; data: LoyaltyConfig; message: string }> {
    const response = await api.put(`/loyalty-config/${id}`, data);
    return response.data;
  }

  async activateLoyaltyConfig(id: string): Promise<{ success: boolean; data: LoyaltyConfig; message: string }> {
    const response = await api.post(`/loyalty-config/${id}/activate`);
    return response.data;
  }

  async deleteLoyaltyConfig(id: string): Promise<{ success: boolean; message: string }> {
    const response = await api.delete(`/loyalty-config/${id}`);
    return response.data;
  }

  // Utility methods
  getTierColor(tier: string): string {
    switch (tier) {
      case 'bronze':
        return '#CD7F32';
      case 'silver':
        return '#C0C0C0';
      case 'gold':
        return '#FFD700';
      case 'platinum':
        return '#E5E4E2';
      default:
        return '#6B7280';
    }
  }

  getTierIcon(tier: string): string {
    switch (tier) {
      case 'bronze':
        return '🥉';
      case 'silver':
        return '🥈';
      case 'gold':
        return '🥇';
      case 'platinum':
        return '💎';
      default:
        return '💳';
    }
  }

  formatPoints(points: number): string {
    return points.toLocaleString();
  }

  calculateDiscountValue(points: number, redemptionRate: number): number {
    return Math.floor(points / redemptionRate);
  }

  calculatePointsFromAmount(amount: number, pointsPerDollar: number): number {
    return Math.floor(amount * pointsPerDollar);
  }
}

const loyaltyCardService = new LoyaltyCardService();

export default loyaltyCardService;
