import React, { useState, useRef, useCallback } from 'react';
import { useForm } from 'react-hook-form';
import { Building, Upload, Trash2, Eye, X } from 'lucide-react';
import { Company, Currency, CostingMethod } from '../types';
import { 
  businessTypeOptions, 
  industryOptions, 
  timezoneOptions,
  logoUploadConfig 
} from '../data/companySetupModules';
import './CompanySetupForm.css';

interface CompanySetupFormData {
  name: string;
  code?: string; // Optional - auto-generated by backend
  email: string;
  phone: string;
  website?: string;
  address: string;
  country?: string;
  region?: string;
  description?: string;
  businessType?: string;
  industry?: string;
  businessRegistrationNumber?: string;
  timezone?: string;
  tin?: string;
  vrn?: string;
  fax?: string;
  defaultCurrencyId: string;
  costingMethod: string;
  efdSettings?: string;
}

interface CompanySetupFormProps {
  company?: Company | null;
  currencies: Currency[];
  costingMethods: CostingMethod[];
  onSubmit: (data: CompanySetupFormData, logoFile?: File) => Promise<void>;
  onCancel: () => void;
  isLoading?: boolean;
  isSaving?: boolean;
  isUploading?: boolean;
}

const CompanySetupForm: React.FC<CompanySetupFormProps> = ({
  company,
  currencies,
  costingMethods,
  onSubmit,
  onCancel,
  isLoading = false,
  isSaving = false,
  isUploading = false
}) => {
  const [logoFile, setLogoFile] = useState<File | null>(null);
  const [logoPreview, setLogoPreview] = useState<string | null>(
    company?.logo ? `http://localhost:3000${company.logo}` : null
  );
  const [showLogoPreview, setShowLogoPreview] = useState(false);
  const fileInputRef = useRef<HTMLInputElement>(null);

  const {
    register,
    handleSubmit,
    formState: { errors },
    setValue,
    watch,
    reset
  } = useForm<CompanySetupFormData>({
    defaultValues: {
      name: company?.name || '',
      email: company?.email || '',
      phone: company?.phone || '',
      website: company?.website || '',
      address: company?.address || '',
      country: company?.country || 'Tanzania',
      region: company?.region || '',
      description: company?.description || '',
      businessType: company?.businessType || '',
      industry: company?.industry || '',
      businessRegistrationNumber: company?.businessRegistrationNumber || '',
      timezone: company?.timezone || 'Africa/Dar_es_Salaam',
      tin: company?.tin || '',
      vrn: company?.vrn || '',
      fax: company?.fax || '',
      defaultCurrencyId: company?.defaultCurrencyId || '',
      costingMethod: company?.costingMethod || '',
      efdSettings: company?.efdSettings || ''
    }
  });

  // Handle logo file selection
  const handleLogoSelect = useCallback((event: React.ChangeEvent<HTMLInputElement>) => {
    const file = event.target.files?.[0];
    if (!file) return;

    // Validate file type
    if (!logoUploadConfig.allowedTypes.includes(file.type)) {
      alert('Invalid file type. Please upload PNG, JPG, or SVG files.');
      return;
    }

    // Validate file size
    if (file.size > logoUploadConfig.maxSize) {
      alert('File size too large. Maximum size is 2MB.');
      return;
    }

    setLogoFile(file);

    // Create preview
    const reader = new FileReader();
    reader.onload = (e) => {
      setLogoPreview(e.target?.result as string);
    };
    reader.readAsDataURL(file);
  }, []);

  // Handle logo upload button click
  const handleUploadClick = useCallback(() => {
    fileInputRef.current?.click();
  }, []);

  // Handle logo removal
  const handleRemoveLogo = useCallback(() => {
    setLogoFile(null);
    setLogoPreview(null);
    if (fileInputRef.current) {
      fileInputRef.current.value = '';
    }
  }, []);

  // Handle form submission
  const handleFormSubmit = useCallback(async (data: CompanySetupFormData) => {
    try {
      await onSubmit(data, logoFile || undefined);
    } catch (error) {
      // Error is already handled by the parent component with toast notifications
    }
  }, [onSubmit, logoFile]);

  // Format file size
  const formatFileSize = useCallback((bytes: number): string => {
    if (bytes === 0) return '0 Bytes';
    const k = 1024;
    const sizes = ['Bytes', 'KB', 'MB', 'GB'];
    const i = Math.floor(Math.log(bytes) / Math.log(k));
    return parseFloat((bytes / Math.pow(k, i)).toFixed(2)) + ' ' + sizes[i];
  }, []);

  return (
    <form onSubmit={handleSubmit(handleFormSubmit)} className="company-setup-form">
      {/* Company Details Card */}
      <div className="form-card">
        <div className="card-header">
          <Building size={20} />
          <h4>Company Details</h4>
        </div>
        <div className="form-grid">
          <div className="form-group">
            <label htmlFor="name" className="form-label">
              Company Name *
            </label>
            <input
              type="text"
              id="name"
              {...register('name', { required: 'Company name is required' })}
              className={`form-input ${errors.name ? 'error' : ''}`}
              placeholder="Enter company name"
              disabled={isLoading}
            />
            {errors.name && (
              <span className="error-message">{errors.name.message}</span>
            )}
          </div>

          <div className="form-group">
            <label htmlFor="code" className="form-label">
              Company Code
            </label>
            <input
              type="text"
              id="code"
              value={company ? (company.code || '') : 'Auto-generated (e.g., HAM)'}
              className="form-input bg-gray-50 text-gray-600 cursor-not-allowed border-gray-300 font-mono font-semibold"
              disabled
              readOnly
            />
            <small className="form-help">Code is automatically generated from company name</small>
          </div>

          <div className="form-group">
            <label htmlFor="email" className="form-label">
              Email *
            </label>
            <input
              type="email"
              id="email"
              {...register('email', { 
                required: 'Email is required',
                pattern: { value: /^[^\s@]+@[^\s@]+\.[^\s@]+$/, message: 'Invalid email format' }
              })}
              className={`form-input ${errors.email ? 'error' : ''}`}
              placeholder="Enter email address"
              disabled={isLoading}
            />
            {errors.email && (
              <span className="error-message">{errors.email.message}</span>
            )}
          </div>

          <div className="form-group">
            <label htmlFor="phone" className="form-label">
              Phone *
            </label>
            <input
              type="tel"
              id="phone"
              {...register('phone', { required: 'Phone number is required' })}
              className={`form-input ${errors.phone ? 'error' : ''}`}
              placeholder="Enter phone number"
              disabled={isLoading}
            />
            {errors.phone && (
              <span className="error-message">{errors.phone.message}</span>
            )}
          </div>

          <div className="form-group">
            <label htmlFor="website" className="form-label">
              Website
            </label>
            <input
              type="url"
              id="website"
              {...register('website', {
                pattern: { value: /^https?:\/\/.+/, message: 'Invalid website URL' }
              })}
              className={`form-input ${errors.website ? 'error' : ''}`}
              placeholder="https://www.example.com"
              disabled={isLoading}
            />
            {errors.website && (
              <span className="error-message">{errors.website.message}</span>
            )}
          </div>

          <div className="form-group">
            <label htmlFor="logo" className="form-label">
              Company Logo
            </label>
            <div className="logo-upload-container">
              <div className="logo-preview" onClick={() => logoPreview && setShowLogoPreview(true)}>
                {logoPreview ? (
                  <img src={logoPreview} alt="Company Logo" className="logo-image" />
                ) : (
                  <div className="logo-placeholder">
                    <Building size={48} />
                    <span>No logo uploaded</span>
                  </div>
                )}
              </div>
              <div className="logo-upload-controls">
                <input
                  ref={fileInputRef}
                  type="file"
                  accept="image/*"
                  onChange={handleLogoSelect}
                  style={{ display: 'none' }}
                />
                <button
                  type="button"
                  className="btn btn-secondary"
                  onClick={handleUploadClick}
                  disabled={isUploading}
                >
                  <Upload size={16} />
                  {isUploading ? 'Uploading...' : 'Upload Logo'}
                </button>
                {logoPreview && (
                  <button
                    type="button"
                    className="btn btn-outline"
                    onClick={handleRemoveLogo}
                    disabled={isUploading}
                  >
                    <Trash2 size={16} />
                    Remove
                  </button>
                )}
              </div>
              <small className="form-help">
                Upload your company logo (PNG, JPG, SVG - max 2MB)
                {logoFile && (
                  <span className="file-info">
                    Selected: {logoFile.name} ({formatFileSize(logoFile.size)})
                  </span>
                )}
              </small>
            </div>
          </div>

          <div className="form-group full-width">
            <label htmlFor="address" className="form-label">
              Address *
            </label>
            <input
              type="text"
              id="address"
              {...register('address', { required: 'Address is required' })}
              className={`form-input ${errors.address ? 'error' : ''}`}
              placeholder="Enter full address"
              disabled={isLoading}
            />
            {errors.address && (
              <span className="error-message">{errors.address.message}</span>
            )}
          </div>

          <div className="form-group">
            <label htmlFor="country" className="form-label">
              Country
            </label>
            <input
              type="text"
              id="country"
              {...register('country')}
              className="form-input"
              placeholder="e.g., Tanzania"
              disabled={isLoading}
            />
          </div>

          <div className="form-group">
            <label htmlFor="region" className="form-label">
              Region
            </label>
            <input
              type="text"
              id="region"
              {...register('region')}
              className="form-input"
              placeholder="e.g., Dar es Salaam"
              disabled={isLoading}
            />
          </div>

          <div className="form-group full-width">
            <label htmlFor="description" className="form-label">
              Description
            </label>
            <textarea
              id="description"
              {...register('description')}
              className="form-textarea"
              rows={3}
              placeholder="Enter company description"
              disabled={isLoading}
            />
          </div>
        </div>
      </div>

      {/* Business Information Card */}
      <div className="form-card">
        <div className="card-header">
          <Building size={20} />
          <h4>Business Information</h4>
        </div>
        <div className="form-grid">
          <div className="form-group">
            <label htmlFor="businessType" className="form-label">
              Business Type
            </label>
            <select
              id="businessType"
              {...register('businessType')}
              className="form-select"
              disabled={isLoading}
            >
              <option value="">Select Business Type</option>
              {businessTypeOptions.map(option => (
                <option key={option.value} value={option.value}>
                  {option.label}
                </option>
              ))}
            </select>
          </div>

          <div className="form-group">
            <label htmlFor="industry" className="form-label">
              Industry
            </label>
            <select
              id="industry"
              {...register('industry')}
              className="form-select"
              disabled={isLoading}
            >
              <option value="">Select Industry</option>
              {industryOptions.map(option => (
                <option key={option.value} value={option.value}>
                  {option.label}
                </option>
              ))}
            </select>
          </div>

          <div className="form-group">
            <label htmlFor="businessRegistrationNumber" className="form-label">
              Business Registration No.
            </label>
            <input
              type="text"
              id="businessRegistrationNumber"
              {...register('businessRegistrationNumber')}
              className="form-input"
              placeholder="Enter registration number"
              disabled={isLoading}
            />
          </div>

          <div className="form-group">
            <label htmlFor="timezone" className="form-label">
              Timezone
            </label>
            <select
              id="timezone"
              {...register('timezone')}
              className="form-select"
              disabled={isLoading}
            >
              {timezoneOptions.map(option => (
                <option key={option.value} value={option.value}>
                  {option.label}
                </option>
              ))}
            </select>
          </div>
        </div>
      </div>

      {/* Tax & Legal Information Card */}
      <div className="form-card">
        <div className="card-header">
          <Building size={20} />
          <h4>Tax & Legal Information</h4>
        </div>
        <div className="form-grid">
          <div className="form-group">
            <label htmlFor="tin" className="form-label">
              TIN No.
            </label>
            <input
              type="text"
              id="tin"
              {...register('tin')}
              className="form-input"
              placeholder="Enter TIN number"
              disabled={isLoading}
            />
          </div>

          <div className="form-group">
            <label htmlFor="vrn" className="form-label">
              VRN
            </label>
            <input
              type="text"
              id="vrn"
              {...register('vrn')}
              className="form-input"
              placeholder="Enter VRN"
              disabled={isLoading}
            />
          </div>

          <div className="form-group">
            <label htmlFor="fax" className="form-label">
              Fax
            </label>
            <input
              type="text"
              id="fax"
              {...register('fax')}
              className="form-input"
              placeholder="Enter fax number"
              disabled={isLoading}
            />
          </div>
        </div>
      </div>

      {/* Financial Settings Card */}
      <div className="form-card">
        <div className="card-header">
          <Building size={20} />
          <h4>Financial Settings</h4>
        </div>
        <div className="form-grid">
          <div className="form-group">
            <label htmlFor="defaultCurrencyId" className="form-label">
              Default Currency *
            </label>
            <select
              id="defaultCurrencyId"
              {...register('defaultCurrencyId', { required: 'Default currency is required' })}
              className={`form-select ${errors.defaultCurrencyId ? 'error' : ''}`}
              disabled={isLoading}
            >
              <option value="">Select Currency</option>
              {currencies.map(currency => (
                <option key={currency.id} value={currency.id}>
                  {currency.code} - {currency.name}
                </option>
              ))}
            </select>
            {errors.defaultCurrencyId && (
              <span className="error-message">{errors.defaultCurrencyId.message}</span>
            )}
          </div>

          <div className="form-group">
            <label htmlFor="costingMethod" className="form-label">
              Costing Method *
            </label>
            <select
              id="costingMethod"
              {...register('costingMethod', { required: 'Costing method is required' })}
              className={`form-select ${errors.costingMethod ? 'error' : ''}`}
              disabled={isLoading}
            >
              <option value="">Select Method</option>
              {costingMethods.map(method => (
                <option key={method.id} value={method.id}>
                  {method.name} ({method.code})
                </option>
              ))}
            </select>
            {errors.costingMethod && (
              <span className="error-message">{errors.costingMethod.message}</span>
            )}
            <small className="form-help">Choose how inventory costs will be calculated</small>
          </div>

          <div className="form-group">
            <label htmlFor="efdSettings" className="form-label">
              EFD Settings
            </label>
            <input
              type="text"
              id="efdSettings"
              {...register('efdSettings')}
              className="form-input"
              placeholder="Enter EFD settings"
              disabled={isLoading}
            />
          </div>
        </div>
      </div>

      {/* Form Actions */}
      <div className="form-actions">
        <button
          type="button"
          className="btn btn-secondary"
          onClick={onCancel}
          disabled={isSaving}
        >
          <X size={16} />
          Cancel
        </button>
        <button
          type="submit"
          className="btn btn-primary"
          disabled={isLoading || isSaving}
        >
          {isSaving ? (
            <>
              <div className="spinner" />
              Saving...
            </>
          ) : (
            <>
              <Building size={16} />
              Save Details
            </>
          )}
        </button>
      </div>

      {/* Logo Preview Modal */}
      {showLogoPreview && logoPreview && (
        <div className="modal-overlay" onClick={() => setShowLogoPreview(false)}>
          <div className="modal-content" onClick={(e) => e.stopPropagation()}>
            <div className="modal-header">
              <h3>Logo Preview</h3>
              <button
                type="button"
                className="modal-close"
                onClick={() => setShowLogoPreview(false)}
              >
                <X size={20} />
              </button>
            </div>
            <div className="modal-body">
              <img src={logoPreview} alt="Company Logo Preview" className="logo-preview-full" />
            </div>
          </div>
        </div>
      )}
    </form>
  );
};

export default CompanySetupForm; 